server:
  port: 8093

spring:
  datasource:
    username: nonroot
    password: nonroot
    url: jdbc:postgresql://localhost:5429/omega

momiji:
  clients:
    gateway:
      stub: false
      url: http://localhost:8091
    neural:
      text-generation:
        stub: false
        url: http://localhost:8090
      speech-caption:
        stub: true
        url:  http://localhost:8092
      image-caption:
        stub: true
        url: http://localhost:8093

logging:
  level:
    com.momiji.api: trace
    com.momiji.bot.service: trace
    com.momiji.bot.controller: trace

ro-bot:
  context-size: 20
  superusers:
    frontend:
      telegram:
        - me

s3:
  region: us-east-1
  host: localhost
  port: 9000
  path: /
  scheme: http
  access-key-id: accessKey1
  secret-access-key: verySecretKey1
