server:
  port: 8081

spring:
  datasource:
    username: nonroot
    password: nonroot
    url: jdbc:postgresql://localhost:5429/gateway

momiji:
  clients:
    gateway:
      stub: true
      url: http://localhost:8080
    neural:
      text:
        stub: true
        url: http://localhost:8080

logging:
  level:
    com.momiji.api: debug

ro-bot:
  context-size: 20
